brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path("", views.todo_list_view, name="todo_list_view"),
    path(
        "todo_list/<int:id>/", views.todo_list_detail, name="todo_list_detail"
    ),
    path(
        "create/", views.TodoListCreateView.as_view(), name="todo_list_create"
    ),
    path(
        "<int:pk>/edit/",
        views.TodoListUpdateView.as_view(),
        name="todo_list_update",
    ),
    path(
        "<int:pk>/delete/",
        views.TodoListDeleteView.as_view(),
        name="todo_list_delete",
    ),
    path(
        "items/create/", views.TodoItemView.as_view(), name="todo_item_create"
    ),
    path(
        "items/<int:pk>/edit/",
        views.TodoItemUpdateView.as_view(),
        name="todo_item_update",
    ),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        TodoList, on_delete=models.CASCADE, related_name="items"
    )


# Create your models here.

todos/views.py
from django.shortcuts import render, get_object_or_404
from todos.models import TodoList, TodoItem
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.


def todo_list_view(request):
    todo_lists = TodoList.objects.all()
    context = {"todo_lists": todo_lists}
    return render(request, "todos/todo_list.html", context)


def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    todo_items = todo_list.items.all()
    context = {"todo_list": todo_list, "todo_items": todo_items}
    return render(request, "todos/todo_list_detail.html", context)


class TodoListCreateView(CreateView):
    model = TodoList
    fields = ["name"]
    template_name = "todos/todo_list_create.html"

    def get_success_url(self):
        return reverse("todos:todo_list_detail", args=[self.object.pk])


class TodoListUpdateView(UpdateView):
    model = TodoList
    fields = ["name"]
    template_name = "todos/todo_list_update.html"

    def get_success_url(self):
        return reverse("todos:todo_list_detail", kwargs={"id": self.object.pk})


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/todo_list_delete.html"

    def get_success_url(self):
        return reverse("todos:todo_list_view")


class TodoItemView(CreateView):
    model = TodoItem
    fields = [
        "task",
        "due_date",
        "is_completed",
        "list",
    ]
    template_name = "todos/todo_item_create.html"

    def get_success_url(self):
        return reverse("todos:todo_list_view")


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    fields = ["task", "due_date", "is_completed", "list"]
    template_name = "todos/todo_item_update.html"

    def get_success_url(self):
        return reverse(
            "todos:todo_list_detail", kwargs={"id": self.object.list.id}
        )

todos/templates/todos/todo_item_create.html
<main>
    <div>
        <h1>Create A New item</h1>
        <form method="post">
            {% csrf_token %}
            {% comment %} #<label for="task">Task:</label>
            <input type="text" id="task" name="task" required><br>
            <label for="due_date">Due Date:</label>
            <input type="text" id="due_date" name="due_date"><br>
            <label for="is_completed">Is Completed:</label>
            <input type="checkbox" id="is_completed" name="is_completed"><br>
            <label for="list">Select List:</label>
            <select name="list">
                {% for todo_list in todo_lists %}
                    <option value={{ todo_list }}></option>
                {% endfor %}
            </select> {% endcomment %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
        <p>
            <a href="{% url 'todos:todo_list_view' %}">Back to List</a>
        </p>
    </div>
</main>

todos/templates/todos/todo_item_update.html
<main>
    <div>
        <h1><a href="{% url 'todos:todo_list_view' %}">Home</a></h1>
        <h2>Update Task</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
</main>

todos/templates/todos/todo_list.html
<main>
    <div>
        <h1>My Lists</h1>
        <p><a href="{% url 'todos:todo_list_create' %}">Create a new list</a></p>
        <h2>
        <p><a href="{% url 'todos:todo_item_create' %}">Create a new item</a></p>
        </h2>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number Of Items</th>
                </tr>
            </thead>
            <tbody>
                {% for todo_list in todo_lists %}
                    <tr>
                        <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
                        <td>{{ todo_list.items.count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>

todos/templates/todos/todo_list_create.html
<main>
    <div>
        <h1>Create A New List</h1>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Create</button>
        </form>
        <p>
            <a href="{% url "todos:todo_list_view" %}">Back to List</a>
        </p>
    </div>
</main>

todos/templates/todos/todo_list_delete.html
<main>
    <div>
        <h1><a href="{% url 'todos:todo_list_view' %}">Home</a></h1>
        <h2>Are you sure?</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
</main>

todos/templates/todos/todo_list_detail.html
<main>
    <div>
        <h1><a href="{% url 'todos:todo_list_view' %}">Home</a></h1>
        </h1>
        <h2>{{ todo_list.name }}</h2>
        <div>
            <div>
                <p><a href="{% url 'todos:todo_list_update' todo_list.id %}">Edit</a></p>
                <p><a href="{% url 'todos:todo_list_delete' todo_list.id %}">Delete</a></p>
            </div>
        <table>
            <thead>
                <tr>
                <th style="font-size: 25px; text-align:left;">Tasks</th>
                </tr>
                <tr>
                    <th>Task</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for item in todo_items %}
                    <tr>
                        <td><a href="{% url 'todos:todo_item_update' item.id %}">{{ item.task }}</a></td>
                        <td>{{ item.due_date|date:"m/d/Y" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>

todos/templates/todos/todo_list_update.html
<main>
    <div>
        <h1><a href="{% url 'todos:todo_list_view' %}">Home</a></h1>
        <h2>Update list</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
</main>